[package]
name = "arc107"
version = "0.1.0"
authors = ["jin237 <fgdaojebvoa237@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
